config/routes.rb
Rails.application.routes.draw do
  root 'feeds#index'
  resources :schedules

end

app/models/feed.rb
class Feed < ActiveRecord::Base


	def self.pull_tweets
    $client.search("#ukraine", count: 500, :result_type => "recent").take(500).each do |tweet|
      
        create!(
          tweet_id: tweet.id,
          content: tweet.text,
          screen_name: tweet.user.screen_name
        )
      
    end
  end
  

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  
  scope :set_cron, ->{where(active: true).map {|c|c.cron}.join(",").html_safe}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  
  def index
  	@crons = Schedule.set_cron
	Rufus::Scheduler.singleton.cron("37 #{@crons} * * *") { Feed.pull_tweets }
  	@feeds = Feed.paginate(:page => params[:page], :per_page => 500).order('created_at DESC')
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

	def index
		@schedules = Schedule.all
	end
  def show
  	
  end
	
	def new
		@schedule = Schedule.new
	end
  
  def edit
  	respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

	def create
		@schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    def set_schedule
    	@schedule = Schedule.find(params[:id])
    end
	  def schedule_params
	  	params.require(:schedule).permit(:cron, :active)
	  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
	def am_pm(hour)
    meridian = (hour >= 12) ? 'pm' : 'am'
    hour = case hour
        when 0, 12
          12
        when 13 .. 23
          hour - 12
        else
          hour
        end

    "#{ hour } #{ meridian }"
  end
end

app/views/feeds/index.html.erb
<h1>Tweet Feeds </h1>
  <%= will_paginate %>
<div class="row">

	<% @feeds.each do |feed| %>
    <div class="col-xs-12 col-md-8">
	  @<%= feed.screen_name %> 
	  <span> | <small> Feed time: <i> <%= feed.created_at %></i></small></span>
	  <%= simple_format(feed.content) %>
	  
	  </div>
	<% end %>

</div>
	<%= will_paginate %>
<%#= @tweets %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Twitter Feed" %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Twitter Feed", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Feed Time",   schedules_path %></li>
           
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  

  <div class="form-group">
    <label class="control-label"><strong>Feed Time</strong></label>
    <%= f.select(:cron, options_for_select([['12 AM', 0],['1 AM', 1],['2 AM', 2], ['3 AM', 3], ['4 AM', 4], ['5 AM', 5], ['6 AM', 6], ['7 AM', 7],['8 AM', 8], ['9 AM', 9],['10 AM', 10], ['11 AM', 11], ['12 PM', 12],['1 PM', 13],['2 PM', 14], ['3 PM', 15], ['4 PM', 16], ['5 PM', 17], ['6 PM', 18], ['7 PM', 19],['8 PM', 20], ['9 PM', 21],['10 PM', 22], ['11 PM', 23]])) %>
  </div>
  <div class="form-group">
    <label class="control-label"><strong>Active</strong></label>
    <%= f.check_box :active %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>


<table>
  <thead>
    <tr>
      <th>Schedule</th>
      
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |s| %>
      <tr>
        <td><%= am_pm(s.cron) %></td>
        
        <td><%= link_to 'Show', s %></td>
        <td><%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1> New Schedule </h1>

<%= render 'form' %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed Time:</strong>
 
  <%= am_pm(@schedule.cron) %>   
</p>

<%= link_to 'Back', schedules_path %>